---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: usr-api-${QUANTUM_DEPLOYMENT_NAME}
  namespace: citadel
  labels:
    deployment: ${QUANTUM_DEPLOYMENT_NAME}
    env: ${QUANTUM_DEPLOYMENT_ENV}
    role: api
    run: usr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      env: ${QUANTUM_DEPLOYMENT_ENV}
      role: api
      run: usr-api
  template:
    metadata:
      labels:
        env: ${QUANTUM_DEPLOYMENT_ENV}
        role: api
        run: usr-api
    spec:
      restartPolicy: Always
      containers:
      - name: usr-api
        image: wizardsofindustry/quantum-usr:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          protocol: TCP
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 50Mi
        env:
        - name: QUANTUM_DEPLOYMENT_ENV
          value: ${QUANTUM_DEPLOYMENT_ENV}
        - name: QUANTUM_DEPLOYMENT_NAME
          value: ${QUANTUM_DEPLOYMENT_NAME}
        - name: USR_RDBMS_DSN
          valueFrom:
            secretKeyRef:
              key: dsn
              name: rdbms.usr
        - name: USR_ROLE
          value: api
        - name: USR_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret_key
              name: application.secret.usr
        envFrom:
        - configMapRef:
            name: config.common.usr
        - configMapRef:
            name: config.${QUANTUM_DEPLOYMENT_ENV}.usr
      volumes: []
      qosClass: Burstable
      imagePullSecrets:
      - name: dockerhub.wizards
