---
apiVersion: v1
kind: Service
metadata:
  namespace: citadel
  name: usr-api
  labels:
    deployment: ${QUANTUM_DEPLOYMENT_NAME}
    env: ${QUANTUM_DEPLOYMENT_ENV}
    run: usr-api
    role: api
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    run: usr-api
    role: api
