"""Create phonenumbers relation

Revision ID: 0f23cbe1aab3
Revises: ade77fcd859c
Create Date: 2018-09-10 09:00:14.811998

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = '0f23cbe1aab3'
down_revision = 'ade77fcd859c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phonenumbers',
    sa.Column('gsid', sq.ext.rdbms.types.UUID(), nullable=False),
    sa.Column('phonenumber', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('phonenumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phonenumbers')
    # ### end Alembic commands ###
