"""Create subjects relation

Revision ID: 2147817b0cbe
Revises: f406c848e440
Create Date: 2018-07-18 12:12:38.951330

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = '2147817b0cbe'
down_revision = 'f406c848e440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
