"""Add idin_bankidentificationnumbers relation

Revision ID: 64373f0628ec
Revises: 0f23cbe1aab3
Create Date: 2018-09-16 13:25:04.241428

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = '64373f0628ec'
down_revision = '0f23cbe1aab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idin_bankidentificationnumbers',
    sa.Column('gsid', sq.ext.rdbms.types.UUID(), nullable=False),
    sa.Column('bin', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idin_bankidentificationnumbers')
    # ### end Alembic commands ###
