"""Add certificatekeyidentifiers

Revision ID: ade77fcd859c
Revises: dd62dc6b60dd
Create Date: 2018-07-18 22:55:46.311960

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = 'ade77fcd859c'
down_revision = 'dd62dc6b60dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificatekeyids',
    sa.Column('gsid', sq.ext.rdbms.types.UUID(), nullable=False),
    sa.Column('keyid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('keyid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificatekeyids')
    # ### end Alembic commands ###
